// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIei7cc9IQFMFfQbpgQ5N3GOOwZwNNtOA',
    appId: '1:513489179244:web:f806defa4e751c7aa6be49',
    messagingSenderId: '513489179244',
    projectId: 'chatapp-22b67',
    authDomain: 'chatapp-22b67.firebaseapp.com',
    storageBucket: 'chatapp-22b67.firebasestorage.app',
    measurementId: 'G-ZFG3XM62TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaMa0qjMWjmIZnfpusxXa9H5a8Hp-CjDA',
    appId: '1:513489179244:android:8155d158a14dc337a6be49',
    messagingSenderId: '513489179244',
    projectId: 'chatapp-22b67',
    storageBucket: 'chatapp-22b67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF2OIaMmX7vh5zfMeNYJxweugQpENxa9c',
    appId: '1:513489179244:ios:5fd53edb0f0b6c10a6be49',
    messagingSenderId: '513489179244',
    projectId: 'chatapp-22b67',
    storageBucket: 'chatapp-22b67.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF2OIaMmX7vh5zfMeNYJxweugQpENxa9c',
    appId: '1:513489179244:ios:5fd53edb0f0b6c10a6be49',
    messagingSenderId: '513489179244',
    projectId: 'chatapp-22b67',
    storageBucket: 'chatapp-22b67.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIei7cc9IQFMFfQbpgQ5N3GOOwZwNNtOA',
    appId: '1:513489179244:web:b61cf5e51b38690ea6be49',
    messagingSenderId: '513489179244',
    projectId: 'chatapp-22b67',
    authDomain: 'chatapp-22b67.firebaseapp.com',
    storageBucket: 'chatapp-22b67.firebasestorage.app',
    measurementId: 'G-XHHX2KQVBT',
  );
}
